// AUTO-GENERATED by scripts/generate-demo-sections.mjs — DO NOT EDIT BY HAND.
// Run `pnpm --filter @knitui/demo generate:sections` to regenerate after changing
// any `*.stories.tsx`. Sourced from the web Storybook so the mobile gallery
// (Expo `apps/app`) stays in sync with it.
import { type ComponentType, lazy, type LazyExoticComponent } from "react";

import { loadGraphicsRuntime } from "@knitui/graphics/runtime";

import { CanvasGallerySection } from "./CanvasGallerySection";
import { MapSection } from "./MapSection";
import { MediaSection } from "./MediaSection";
import { StorySection } from "./StorySection";

export type DemoSection = {
  /** Stable, URL-safe identifier (the story file's component name). */
  id: string;
  /** Human-readable label shown in navigation. */
  title: string;
  /** Storybook sidebar group the story belongs to (e.g. "Inputs"). */
  group: string;
  /**
   * Whether the section fills the demo's content pane instead of sizing to
   * content. True for map stories (rendered by `MapSection`), so `DemoScreen`
   * gives them the whole canvas rather than the padded, scrolling layout.
   */
  fullBleed: boolean;
  Component: LazyExoticComponent<ComponentType>;
};

/**
 * Every demo section, one per Storybook story module, ordered by group then
 * title. Each `Component` is `React.lazy`'d so a section's module is only
 * evaluated when rendered (the Expo app navigates one at a time). Both apps
 * consume this as the single source of truth.
 */
export const demoSections: DemoSection[] = [
  {
    id: "Camera",
    title: "Camera",
    group: "Camera",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/Camera/Camera.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Camera" />,
      })),
    ),
  },
  {
    id: "ThemeIcon",
    title: "ThemeIcon",
    group: "Data display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/ThemeIcon/ThemeIcon.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="ThemeIcon" />,
      })),
    ),
  },
  {
    id: "List",
    title: "List",
    group: "Data Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/List/List.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="List" />,
      })),
    ),
  },
  {
    id: "Marquee",
    title: "Marquee",
    group: "Data Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Marquee/Marquee.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Marquee" />,
      })),
    ),
  },
  {
    id: "Table",
    title: "Table",
    group: "Data Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Table/Table.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Table" />,
      })),
    ),
  },
  {
    id: "Tree",
    title: "Tree",
    group: "Data Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Tree/Tree.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Tree" />,
      })),
    ),
  },
  {
    id: "TreeSelect",
    title: "TreeSelect",
    group: "Data Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/TreeSelect/TreeSelect.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="TreeSelect" />,
      })),
    ),
  },
  {
    id: "AmPmInput",
    title: "AmPmInput",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/AmPmInput/AmPmInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="AmPmInput" />,
      })),
    ),
  },
  {
    id: "Calendar",
    title: "Calendar",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/Calendar/Calendar.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Calendar" />,
      })),
    ),
  },
  {
    id: "CalendarHeader",
    title: "CalendarHeader",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/CalendarHeader/CalendarHeader.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="CalendarHeader" />,
      })),
    ),
  },
  {
    id: "DateInput",
    title: "DateInput",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/DateInput/DateInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="DateInput" />,
      })),
    ),
  },
  {
    id: "DatePicker",
    title: "DatePicker",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/DatePicker/DatePicker.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="DatePicker" />,
      })),
    ),
  },
  {
    id: "DatePickerInput",
    title: "DatePickerInput",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/DatePickerInput/DatePickerInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="DatePickerInput" />,
      })),
    ),
  },
  {
    id: "DateTimePicker",
    title: "DateTimePicker",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/DateTimePicker/DateTimePicker.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="DateTimePicker" />,
      })),
    ),
  },
  {
    id: "Day",
    title: "Day",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/Day/Day.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Day" />,
      })),
    ),
  },
  {
    id: "DecadeLevel",
    title: "DecadeLevel",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/DecadeLevel/DecadeLevel.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="DecadeLevel" />,
      })),
    ),
  },
  {
    id: "DecadeLevelGroup",
    title: "DecadeLevelGroup",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/DecadeLevelGroup/DecadeLevelGroup.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="DecadeLevelGroup" />,
      })),
    ),
  },
  {
    id: "LevelsGroup",
    title: "LevelsGroup",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/LevelsGroup/LevelsGroup.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="LevelsGroup" />,
      })),
    ),
  },
  {
    id: "MiniCalendar",
    title: "MiniCalendar",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/MiniCalendar/MiniCalendar.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="MiniCalendar" />,
      })),
    ),
  },
  {
    id: "Month",
    title: "Month",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/Month/Month.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Month" />,
      })),
    ),
  },
  {
    id: "MonthLevel",
    title: "MonthLevel",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/MonthLevel/MonthLevel.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="MonthLevel" />,
      })),
    ),
  },
  {
    id: "MonthLevelGroup",
    title: "MonthLevelGroup",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/MonthLevelGroup/MonthLevelGroup.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="MonthLevelGroup" />,
      })),
    ),
  },
  {
    id: "MonthPicker",
    title: "MonthPicker",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/MonthPicker/MonthPicker.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="MonthPicker" />,
      })),
    ),
  },
  {
    id: "MonthPickerInput",
    title: "MonthPickerInput",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/MonthPickerInput/MonthPickerInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="MonthPickerInput" />,
      })),
    ),
  },
  {
    id: "MonthsList",
    title: "MonthsList",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/MonthsList/MonthsList.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="MonthsList" />,
      })),
    ),
  },
  {
    id: "PickerControl",
    title: "PickerControl",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/PickerControl/PickerControl.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="PickerControl" />,
      })),
    ),
  },
  {
    id: "PickerInputBase",
    title: "PickerInputBase",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/PickerInputBase/PickerInputBase.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="PickerInputBase" />,
      })),
    ),
  },
  {
    id: "SpinInput",
    title: "SpinInput",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/SpinInput/SpinInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="SpinInput" />,
      })),
    ),
  },
  {
    id: "TimeControlsList",
    title: "TimeControlsList",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/TimeControlsList/TimeControlsList.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="TimeControlsList" />,
      })),
    ),
  },
  {
    id: "TimeGrid",
    title: "TimeGrid",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/TimeGrid/TimeGrid.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="TimeGrid" />,
      })),
    ),
  },
  {
    id: "TimeInput",
    title: "TimeInput",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/TimeInput/TimeInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="TimeInput" />,
      })),
    ),
  },
  {
    id: "TimePicker",
    title: "TimePicker",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/TimePicker/TimePicker.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="TimePicker" />,
      })),
    ),
  },
  {
    id: "TimePresets",
    title: "TimePresets",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/TimePresets/TimePresets.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="TimePresets" />,
      })),
    ),
  },
  {
    id: "TimeValue",
    title: "TimeValue",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/TimeValue/TimeValue.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="TimeValue" />,
      })),
    ),
  },
  {
    id: "WeekdaysRow",
    title: "WeekdaysRow",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/WeekdaysRow/WeekdaysRow.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="WeekdaysRow" />,
      })),
    ),
  },
  {
    id: "YearLevel",
    title: "YearLevel",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/YearLevel/YearLevel.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="YearLevel" />,
      })),
    ),
  },
  {
    id: "YearLevelGroup",
    title: "YearLevelGroup",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/YearLevelGroup/YearLevelGroup.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="YearLevelGroup" />,
      })),
    ),
  },
  {
    id: "YearPicker",
    title: "YearPicker",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/YearPicker/YearPicker.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="YearPicker" />,
      })),
    ),
  },
  {
    id: "YearPickerInput",
    title: "YearPickerInput",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/YearPickerInput/YearPickerInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="YearPickerInput" />,
      })),
    ),
  },
  {
    id: "YearsList",
    title: "YearsList",
    group: "Dates",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/YearsList/YearsList.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="YearsList" />,
      })),
    ),
  },
  {
    id: "ExampleControl",
    title: "ExampleControl",
    group: "Dates / _Reference",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/dates/src/_reference/ExampleControl.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="ExampleControl" />,
      })),
    ),
  },
  {
    id: "Avatar",
    title: "Avatar",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Avatar/Avatar.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Avatar" />,
      })),
    ),
  },
  {
    id: "BackgroundImage",
    title: "BackgroundImage",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/BackgroundImage/BackgroundImage.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="BackgroundImage" />,
      })),
    ),
  },
  {
    id: "Badge",
    title: "Badge",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Badge/Badge.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Badge" />,
      })),
    ),
  },
  {
    id: "Card",
    title: "Card",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Card/Card.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Card" />,
      })),
    ),
  },
  {
    id: "ColorSwatch",
    title: "ColorSwatch",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/ColorSwatch/ColorSwatch.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="ColorSwatch" />,
      })),
    ),
  },
  {
    id: "Image",
    title: "Image",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Image/Image.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Image" />,
      })),
    ),
  },
  {
    id: "Indicator",
    title: "Indicator",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Indicator/Indicator.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Indicator" />,
      })),
    ),
  },
  {
    id: "Loader",
    title: "Loader",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Loader/Loader.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Loader" />,
      })),
    ),
  },
  {
    id: "Overlay",
    title: "Overlay",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Overlay/Overlay.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Overlay" />,
      })),
    ),
  },
  {
    id: "Pill",
    title: "Pill",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Pill/Pill.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Pill" />,
      })),
    ),
  },
  {
    id: "Progress",
    title: "Progress",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Progress/Progress.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Progress" />,
      })),
    ),
  },
  {
    id: "RollingNumber",
    title: "RollingNumber",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/RollingNumber/RollingNumber.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="RollingNumber" />,
      })),
    ),
  },
  {
    id: "Separator",
    title: "Separator",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Separator/Separator.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Separator" />,
      })),
    ),
  },
  {
    id: "Skeleton",
    title: "Skeleton",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Skeleton/Skeleton.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Skeleton" />,
      })),
    ),
  },
  {
    id: "VisuallyHidden",
    title: "VisuallyHidden",
    group: "Display",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/VisuallyHidden/VisuallyHidden.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="VisuallyHidden" />,
      })),
    ),
  },
  {
    id: "Alert",
    title: "Alert",
    group: "Feedback",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Alert/Alert.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Alert" />,
      })),
    ),
  },
  {
    id: "LoadingOverlay",
    title: "LoadingOverlay",
    group: "Feedback",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/LoadingOverlay/LoadingOverlay.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="LoadingOverlay" />,
      })),
    ),
  },
  {
    id: "Notification",
    title: "Notification",
    group: "Feedback",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Notification/Notification.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Notification" />,
      })),
    ),
  },
  {
    id: "Spoiler",
    title: "Spoiler",
    group: "Feedback",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Spoiler/Spoiler.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Spoiler" />,
      })),
    ),
  },
  {
    id: "AudioMesh",
    title: "AudioMesh",
    group: "Graphics",
    fullBleed: false,
    Component: lazy(() =>
      loadGraphicsRuntime()
        .then(() => import("@knitui/graphics/src/components/AudioViz/AudioMesh.stories"))
        .then((m) => ({
          default: () => (
            <CanvasGallerySection mod={m as Record<string, unknown>} title="AudioMesh" />
          ),
        })),
    ),
  },
  {
    id: "AudioVisualizer",
    title: "AudioVisualizer",
    group: "Graphics",
    fullBleed: false,
    Component: lazy(() =>
      loadGraphicsRuntime()
        .then(() => import("@knitui/graphics/src/components/AudioViz/AudioVisualizer.stories"))
        .then((m) => ({
          default: () => (
            <CanvasGallerySection mod={m as Record<string, unknown>} title="AudioVisualizer" />
          ),
        })),
    ),
  },
  {
    id: "GraphicsProvider",
    title: "GraphicsProvider",
    group: "Graphics / Core",
    fullBleed: false,
    Component: lazy(() =>
      loadGraphicsRuntime()
        .then(() => import("@knitui/graphics/src/provider/GraphicsProvider.stories"))
        .then((m) => ({
          default: () => (
            <CanvasGallerySection mod={m as Record<string, unknown>} title="GraphicsProvider" />
          ),
        })),
    ),
  },
  {
    id: "EffectView",
    title: "EffectView",
    group: "Graphics / Effects",
    fullBleed: false,
    Component: lazy(() =>
      loadGraphicsRuntime()
        .then(() => import("@knitui/graphics/src/components/EffectView/EffectView.stories"))
        .then((m) => ({
          default: () => (
            <CanvasGallerySection mod={m as Record<string, unknown>} title="EffectView" />
          ),
        })),
    ),
  },
  {
    id: "ShadowView",
    title: "ShadowView",
    group: "Graphics / Effects",
    fullBleed: false,
    Component: lazy(() =>
      loadGraphicsRuntime()
        .then(() => import("@knitui/graphics/src/components/ShadowView/ShadowView.stories"))
        .then((m) => ({
          default: () => (
            <CanvasGallerySection mod={m as Record<string, unknown>} title="ShadowView" />
          ),
        })),
    ),
  },
  {
    id: "ActionIcon",
    title: "ActionIcon",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/ActionIcon/ActionIcon.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="ActionIcon" />,
      })),
    ),
  },
  {
    id: "AngleSlider",
    title: "AngleSlider",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/AngleSlider/AngleSlider.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="AngleSlider" />,
      })),
    ),
  },
  {
    id: "Autocomplete",
    title: "Autocomplete",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Autocomplete/Autocomplete.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Autocomplete" />,
      })),
    ),
  },
  {
    id: "Button",
    title: "Button",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Button/Button.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Button" />,
      })),
    ),
  },
  {
    id: "Checkbox",
    title: "Checkbox",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Checkbox/Checkbox.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Checkbox" />,
      })),
    ),
  },
  {
    id: "Chip",
    title: "Chip",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Chip/Chip.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Chip" />,
      })),
    ),
  },
  {
    id: "CloseButton",
    title: "CloseButton",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/CloseButton/CloseButton.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="CloseButton" />,
      })),
    ),
  },
  {
    id: "ColorInput",
    title: "ColorInput",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/ColorInput/ColorInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="ColorInput" />,
      })),
    ),
  },
  {
    id: "ColorPicker",
    title: "ColorPicker",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/ColorPicker/ColorPicker.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="ColorPicker" />,
      })),
    ),
  },
  {
    id: "Combobox",
    title: "Combobox",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Combobox/Combobox.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Combobox" />,
      })),
    ),
  },
  {
    id: "CopyButton",
    title: "CopyButton",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/CopyButton/CopyButton.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="CopyButton" />,
      })),
    ),
  },
  {
    id: "Fieldset",
    title: "Fieldset",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Fieldset/Fieldset.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Fieldset" />,
      })),
    ),
  },
  {
    id: "FileButton",
    title: "FileButton",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/FileButton/FileButton.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="FileButton" />,
      })),
    ),
  },
  {
    id: "FileInput",
    title: "FileInput",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/FileInput/FileInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="FileInput" />,
      })),
    ),
  },
  {
    id: "Input",
    title: "Input",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Input/Input.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Input" />,
      })),
    ),
  },
  {
    id: "InputBase",
    title: "InputBase",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/InputBase/InputBase.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="InputBase" />,
      })),
    ),
  },
  {
    id: "MaskInput",
    title: "MaskInput",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/MaskInput/MaskInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="MaskInput" />,
      })),
    ),
  },
  {
    id: "MultiSelect",
    title: "MultiSelect",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/MultiSelect/MultiSelect.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="MultiSelect" />,
      })),
    ),
  },
  {
    id: "NativeSelect",
    title: "NativeSelect",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/NativeSelect/NativeSelect.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="NativeSelect" />,
      })),
    ),
  },
  {
    id: "NumberInput",
    title: "NumberInput",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/NumberInput/NumberInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="NumberInput" />,
      })),
    ),
  },
  {
    id: "PasswordInput",
    title: "PasswordInput",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/PasswordInput/PasswordInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="PasswordInput" />,
      })),
    ),
  },
  {
    id: "PillsInput",
    title: "PillsInput",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/PillsInput/PillsInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="PillsInput" />,
      })),
    ),
  },
  {
    id: "PinInput",
    title: "PinInput",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/PinInput/PinInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="PinInput" />,
      })),
    ),
  },
  {
    id: "Radio",
    title: "Radio",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Radio/Radio.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Radio" />,
      })),
    ),
  },
  {
    id: "Rating",
    title: "Rating",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Rating/Rating.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Rating" />,
      })),
    ),
  },
  {
    id: "SegmentedControl",
    title: "SegmentedControl",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/SegmentedControl/SegmentedControl.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="SegmentedControl" />,
      })),
    ),
  },
  {
    id: "Select",
    title: "Select",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Select/Select.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Select" />,
      })),
    ),
  },
  {
    id: "Slider",
    title: "Slider",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Slider/Slider.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Slider" />,
      })),
    ),
  },
  {
    id: "Switch",
    title: "Switch",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Switch/Switch.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Switch" />,
      })),
    ),
  },
  {
    id: "TagsInput",
    title: "TagsInput",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/TagsInput/TagsInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="TagsInput" />,
      })),
    ),
  },
  {
    id: "Textarea",
    title: "Textarea",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Textarea/Textarea.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Textarea" />,
      })),
    ),
  },
  {
    id: "TextInput",
    title: "TextInput",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/TextInput/TextInput.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="TextInput" />,
      })),
    ),
  },
  {
    id: "UnstyledButton",
    title: "UnstyledButton",
    group: "Inputs",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/UnstyledButton/UnstyledButton.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="UnstyledButton" />,
      })),
    ),
  },
  {
    id: "BackgroundLayer",
    title: "Background Layer",
    group: "Layers",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/BackgroundLayer/BackgroundLayer.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Background Layer" />,
      })),
    ),
  },
  {
    id: "CircleLayer",
    title: "Circle Layer",
    group: "Layers",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/CircleLayer/CircleLayer.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Circle Layer" />,
      })),
    ),
  },
  {
    id: "FillExtrusionLayer",
    title: "Fill Extrusion Layer",
    group: "Layers",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/FillExtrusionLayer/FillExtrusionLayer.stories").then(
        (m) => ({
          default: () => (
            <MapSection mod={m as Record<string, unknown>} title="Fill Extrusion Layer" />
          ),
        }),
      ),
    ),
  },
  {
    id: "FillLayer",
    title: "Fill Layer",
    group: "Layers",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/FillLayer/FillLayer.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Fill Layer" />,
      })),
    ),
  },
  {
    id: "HeatmapLayer",
    title: "Heatmap Layer",
    group: "Layers",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/HeatmapLayer/HeatmapLayer.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Heatmap Layer" />,
      })),
    ),
  },
  {
    id: "Light",
    title: "Light",
    group: "Layers",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/Light/Light.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Light" />,
      })),
    ),
  },
  {
    id: "LineLayer",
    title: "Line Layer",
    group: "Layers",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/LineLayer/LineLayer.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Line Layer" />,
      })),
    ),
  },
  {
    id: "SymbolLayer",
    title: "Symbol Layer",
    group: "Layers",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/SymbolLayer/SymbolLayer.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Symbol Layer" />,
      })),
    ),
  },
  {
    id: "Affix",
    title: "Affix",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Affix/Affix.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Affix" />,
      })),
    ),
  },
  {
    id: "AspectRatio",
    title: "AspectRatio",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/AspectRatio/AspectRatio.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="AspectRatio" />,
      })),
    ),
  },
  {
    id: "Box",
    title: "Box",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Box/Box.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Box" />,
      })),
    ),
  },
  {
    id: "Center",
    title: "Center",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Center/Center.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Center" />,
      })),
    ),
  },
  {
    id: "Container",
    title: "Container",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Container/Container.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Container" />,
      })),
    ),
  },
  {
    id: "Flex",
    title: "Flex",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Flex/Flex.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Flex" />,
      })),
    ),
  },
  {
    id: "Grid",
    title: "Grid",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Grid/Grid.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Grid" />,
      })),
    ),
  },
  {
    id: "Group",
    title: "Group",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Group/Group.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Group" />,
      })),
    ),
  },
  {
    id: "KeyboardAvoidingView",
    title: "KeyboardAvoidingView",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/KeyboardAvoidingView/KeyboardAvoidingView.stories").then(
        (m) => ({
          default: () => (
            <StorySection mod={m as Record<string, unknown>} title="KeyboardAvoidingView" />
          ),
        }),
      ),
    ),
  },
  {
    id: "KeyboardAwareScrollView",
    title: "KeyboardAwareScrollView",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/KeyboardAwareScrollView/KeyboardAwareScrollView.stories").then(
        (m) => ({
          default: () => (
            <StorySection mod={m as Record<string, unknown>} title="KeyboardAwareScrollView" />
          ),
        }),
      ),
    ),
  },
  {
    id: "Paper",
    title: "Paper",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Paper/Paper.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Paper" />,
      })),
    ),
  },
  {
    id: "SimpleGrid",
    title: "SimpleGrid",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/SimpleGrid/SimpleGrid.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="SimpleGrid" />,
      })),
    ),
  },
  {
    id: "Spacer",
    title: "Spacer",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Spacer/Spacer.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Spacer" />,
      })),
    ),
  },
  {
    id: "Stack",
    title: "Stack",
    group: "Layout",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Stack/Stack.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Stack" />,
      })),
    ),
  },
  {
    id: "Interactivity",
    title: "Interactivity",
    group: "Map",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/MapView/Interactivity.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Interactivity" />,
      })),
    ),
  },
  {
    id: "MapView",
    title: "MapView",
    group: "Map",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/MapView/MapView.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="MapView" />,
      })),
    ),
  },
  {
    id: "MapStyles",
    title: "Styles",
    group: "Map",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/styles/MapStyles.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Styles" />,
      })),
    ),
  },
  {
    id: "Callout",
    title: "Callout",
    group: "Markers & Annotations",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/Callout/Callout.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Callout" />,
      })),
    ),
  },
  {
    id: "Annotation",
    title: "Layer Annotation",
    group: "Markers & Annotations",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/Annotation/Annotation.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Layer Annotation" />,
      })),
    ),
  },
  {
    id: "MarkerView",
    title: "Marker",
    group: "Markers & Annotations",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/MarkerView/MarkerView.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Marker" />,
      })),
    ),
  },
  {
    id: "PointAnnotation",
    title: "View Annotation",
    group: "Markers & Annotations",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/PointAnnotation/PointAnnotation.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="View Annotation" />,
      })),
    ),
  },
  {
    id: "Audio",
    title: "Audio",
    group: "Media",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/media/src/audio/Audio.stories").then((m) => ({
        default: () => <MediaSection mod={m as Record<string, unknown>} title="Audio" />,
      })),
    ),
  },
  {
    id: "AudioSpectrum",
    title: "Audio Visualizer",
    group: "Media",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/media/src/audio/visualizer/AudioSpectrum.stories").then((m) => ({
        default: () => <MediaSection mod={m as Record<string, unknown>} title="Audio Visualizer" />,
      })),
    ),
  },
  {
    id: "AudioPlaylist",
    title: "AudioPlaylist",
    group: "Media",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/media/src/audio/playlist/AudioPlaylist.stories").then((m) => ({
        default: () => <MediaSection mod={m as Record<string, unknown>} title="AudioPlaylist" />,
      })),
    ),
  },
  {
    id: "AudioRecorder",
    title: "AudioRecorder",
    group: "Media",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/media/src/audio/recorder/AudioRecorder.stories").then((m) => ({
        default: () => <MediaSection mod={m as Record<string, unknown>} title="AudioRecorder" />,
      })),
    ),
  },
  {
    id: "LiveAudioMeter",
    title: "LiveAudioMeter",
    group: "Media",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/media/src/audio/stream/LiveAudioMeter.stories").then((m) => ({
        default: () => <MediaSection mod={m as Record<string, unknown>} title="LiveAudioMeter" />,
      })),
    ),
  },
  {
    id: "Video",
    title: "Video",
    group: "Media",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/media/src/video/Video.stories").then((m) => ({
        default: () => <MediaSection mod={m as Record<string, unknown>} title="Video" />,
      })),
    ),
  },
  {
    id: "MediaQuery",
    title: "Playground",
    group: "MediaQuery",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/mediaquery/src/MediaQuery.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Playground" />,
      })),
    ),
  },
  {
    id: "Accordion",
    title: "Accordion",
    group: "Navigation",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Accordion/Accordion.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Accordion" />,
      })),
    ),
  },
  {
    id: "Breadcrumbs",
    title: "Breadcrumbs",
    group: "Navigation",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Breadcrumbs/Breadcrumbs.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Breadcrumbs" />,
      })),
    ),
  },
  {
    id: "Burger",
    title: "Burger",
    group: "Navigation",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Burger/Burger.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Burger" />,
      })),
    ),
  },
  {
    id: "NavLink",
    title: "NavLink",
    group: "Navigation",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/NavLink/NavLink.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="NavLink" />,
      })),
    ),
  },
  {
    id: "Pagination",
    title: "Pagination",
    group: "Navigation",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Pagination/Pagination.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Pagination" />,
      })),
    ),
  },
  {
    id: "ScrollArea",
    title: "ScrollArea",
    group: "Navigation",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/ScrollArea/ScrollArea.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="ScrollArea" />,
      })),
    ),
  },
  {
    id: "Stepper",
    title: "Stepper",
    group: "Navigation",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Stepper/Stepper.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Stepper" />,
      })),
    ),
  },
  {
    id: "TableOfContents",
    title: "TableOfContents",
    group: "Navigation",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/TableOfContents/TableOfContents.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="TableOfContents" />,
      })),
    ),
  },
  {
    id: "Tabs",
    title: "Tabs",
    group: "Navigation",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Tabs/Tabs.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Tabs" />,
      })),
    ),
  },
  {
    id: "Carousel",
    title: "Carousel",
    group: "Other",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/carousel/src/Carousel.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Carousel" />,
      })),
    ),
  },
  {
    id: "Sheet",
    title: "Sheet",
    group: "Other",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/sheet/src/Sheet.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Sheet" />,
      })),
    ),
  },
  {
    id: "Collapse",
    title: "Collapse",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Collapse/Collapse.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Collapse" />,
      })),
    ),
  },
  {
    id: "Dialog",
    title: "Dialog",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Dialog/Dialog.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Dialog" />,
      })),
    ),
  },
  {
    id: "Drawer",
    title: "Drawer",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Drawer/Drawer.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Drawer" />,
      })),
    ),
  },
  {
    id: "FocusTrap",
    title: "FocusTrap",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/FocusTrap/FocusTrap.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="FocusTrap" />,
      })),
    ),
  },
  {
    id: "HoverCard",
    title: "HoverCard",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/HoverCard/HoverCard.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="HoverCard" />,
      })),
    ),
  },
  {
    id: "Menu",
    title: "Menu",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Menu/Menu.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Menu" />,
      })),
    ),
  },
  {
    id: "Modal",
    title: "Modal",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Modal/Modal.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Modal" />,
      })),
    ),
  },
  {
    id: "Motion",
    title: "Motion",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Transition/Motion.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Motion" />,
      })),
    ),
  },
  {
    id: "Popover",
    title: "Popover",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Popover/Popover.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Popover" />,
      })),
    ),
  },
  {
    id: "Portal",
    title: "Portal",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Portal/Portal.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Portal" />,
      })),
    ),
  },
  {
    id: "Tooltip",
    title: "Tooltip",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Tooltip/Tooltip.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Tooltip" />,
      })),
    ),
  },
  {
    id: "Transition",
    title: "Transition",
    group: "Overlays",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Transition/Transition.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Transition" />,
      })),
    ),
  },
  {
    id: "ShapeSource",
    title: "GeoJSON Source",
    group: "Sources",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/ShapeSource/ShapeSource.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="GeoJSON Source" />,
      })),
    ),
  },
  {
    id: "ImageSource",
    title: "Image Source",
    group: "Sources",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/ImageSource/ImageSource.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Image Source" />,
      })),
    ),
  },
  {
    id: "RasterSource",
    title: "Raster Source",
    group: "Sources",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/RasterSource/RasterSource.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="Raster Source" />,
      })),
    ),
  },
  {
    id: "SvgImage",
    title: "SVG Icon",
    group: "Sources",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/SvgImage/SvgImage.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="SVG Icon" />,
      })),
    ),
  },
  {
    id: "Anchor",
    title: "Anchor",
    group: "Typography",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Anchor/Anchor.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Anchor" />,
      })),
    ),
  },
  {
    id: "Blockquote",
    title: "Blockquote",
    group: "Typography",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Blockquote/Blockquote.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Blockquote" />,
      })),
    ),
  },
  {
    id: "Code",
    title: "Code",
    group: "Typography",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Code/Code.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Code" />,
      })),
    ),
  },
  {
    id: "Highlight",
    title: "Highlight",
    group: "Typography",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Highlight/Highlight.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Highlight" />,
      })),
    ),
  },
  {
    id: "Kbd",
    title: "Kbd",
    group: "Typography",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Kbd/Kbd.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Kbd" />,
      })),
    ),
  },
  {
    id: "Mark",
    title: "Mark",
    group: "Typography",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Mark/Mark.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Mark" />,
      })),
    ),
  },
  {
    id: "NumberFormatter",
    title: "NumberFormatter",
    group: "Typography",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/NumberFormatter/NumberFormatter.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="NumberFormatter" />,
      })),
    ),
  },
  {
    id: "Paragraph",
    title: "Paragraph",
    group: "Typography",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Paragraph/Paragraph.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Paragraph" />,
      })),
    ),
  },
  {
    id: "Text",
    title: "Text",
    group: "Typography",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Text/Text.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Text" />,
      })),
    ),
  },
  {
    id: "Title",
    title: "Title",
    group: "Typography",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Title/Title.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Title" />,
      })),
    ),
  },
  {
    id: "Typography",
    title: "Typography",
    group: "Typography",
    fullBleed: false,
    Component: lazy(() =>
      import("@knitui/components/src/Typography/Typography.stories").then((m) => ({
        default: () => <StorySection mod={m as Record<string, unknown>} title="Typography" />,
      })),
    ),
  },
  {
    id: "NativeUserLocation",
    title: "Native User Location",
    group: "User Location",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/NativeUserLocation/NativeUserLocation.stories").then(
        (m) => ({
          default: () => (
            <MapSection mod={m as Record<string, unknown>} title="Native User Location" />
          ),
        }),
      ),
    ),
  },
  {
    id: "UserLocation",
    title: "User Location",
    group: "User Location",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/UserLocation/UserLocation.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="User Location" />,
      })),
    ),
  },
  {
    id: "UserLocationPuck",
    title: "User Location Puck",
    group: "User Location",
    fullBleed: true,
    Component: lazy(() =>
      import("@knitui/map/src/components/UserLocationPuck/UserLocationPuck.stories").then((m) => ({
        default: () => <MapSection mod={m as Record<string, unknown>} title="User Location Puck" />,
      })),
    ),
  },
];
