import {
  type ComponentType,
  createElement,
  Fragment,
  isValidElement,
  memo,
  Component as ReactComponent,
  type ReactElement,
  type ReactNode,
  useEffect,
  useState,
} from "react";

import { Box, Separator, Stack, Text, Title, UnstyledButton } from "@knitui/components";

/**
 * Isolates a single story so a throw in one doesn't take down the rest of the
 * section — a whole component's stories render together, so without this one
 * buggy story would blank the pane. Mirrors Storybook's per-story isolation.
 */
export class StoryErrorBoundary extends ReactComponent<
  { label: string; children: ReactNode },
  { error: Error | null }
> {
  state: { error: Error | null } = { error: null };

  static getDerivedStateFromError(error: Error) {
    return { error };
  }

  render() {
    if (this.state.error) {
      return (
        <Box
          borderWidth={1}
          borderColor="$red7"
          backgroundColor="$red2"
          borderRadius="$sm"
          p="$sm"
          gap="$xs"
        >
          <Text c="$red11" fontWeight="600" fz={13}>
            {this.props.label} failed to render
          </Text>
          <Text c="$red10" fz={12}>
            {this.state.error.message}
          </Text>
        </Box>
      );
    }
    return this.props.children;
  }
}

/**
 * Minimal structural shapes of a Storybook CSF module. We deliberately avoid
 * importing `@storybook/*` here — story files only `import type` from it (the
 * imports are erased at compile time), so the runtime module is just a default
 * `meta` plus named `StoryObj` exports. This renderer mirrors how Storybook
 * resolves a story so the mobile gallery shows exactly what the web Storybook
 * shows. See `sections.generated.tsx` (generated by
 * `scripts/generate-demo-sections.mjs`) for how each story module is wired in.
 */
type StoryContext = {
  args: Record<string, unknown>;
  argTypes: unknown;
  component: ComponentType<unknown> | undefined;
};

type Decorator = (Story: ComponentType, context: StoryContext) => ReactElement;

export type StoryObj = {
  render?: (args: Record<string, unknown>, context: StoryContext) => ReactNode;
  args?: Record<string, unknown>;
  decorators?: Decorator[];
};

export type Meta = {
  title?: string;
  component?: ComponentType<unknown>;
  args?: Record<string, unknown>;
  argTypes?: unknown;
  decorators?: Decorator[];
  render?: (args: Record<string, unknown>, context: StoryContext) => ReactNode;
};

/** Reserved exports that are never stories. */
const RESERVED = new Set(["default", "__namedExportsOrder"]);

function isStory(value: unknown): value is StoryObj {
  return (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value) &&
    !isValidElement(value as object)
  );
}

/** `WithSections` -> `With Sections`, `Variants` -> `Variants`. */
export function humanize(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/_/g, " ");
}

/**
 * A single story-selector chip, shared by the one-story-at-a-time renderers
 * (`MapSection`, `CanvasGallerySection`). Active chip is filled; the rest quiet.
 */
export function StoryTab({
  label,
  active,
  onPress,
}: {
  label: string;
  active: boolean;
  onPress: () => void;
}) {
  return (
    <UnstyledButton
      onPress={onPress}
      px="$sm"
      py="$xxs"
      borderRadius="$sm"
      borderWidth={1}
      borderColor={active ? "$color7" : "$color4"}
      backgroundColor={active ? "$color5" : "transparent"}
      pressStyle={{ backgroundColor: active ? "$color5" : "$color3" }}
    >
      <Text c={active ? "$color12" : "$color11"} fz={12} fontWeight={active ? "600" : "400"}>
        {label}
      </Text>
    </UnstyledButton>
  );
}

/**
 * The named story exports of a CSF module, in declaration order, as
 * `[exportName, story]` pairs — shared by every renderer (`StorySection`,
 * `MapSection`) so they pick up the same stories the web Storybook shows.
 */
export function getStories(mod: Record<string, unknown>): (readonly [string, StoryObj])[] {
  const order = (mod.__namedExportsOrder as string[] | undefined) ?? Object.keys(mod);
  return order
    .filter((name) => !RESERVED.has(name) && isStory(mod[name]))
    .map((name) => [name, mod[name] as StoryObj] as const);
}

export function renderStory(meta: Meta, story: StoryObj): ReactNode {
  const args = { ...meta.args, ...story.args };
  const context: StoryContext = {
    args,
    argTypes: meta.argTypes,
    component: meta.component,
  };

  const Component = meta.component;
  const baseRender =
    story.render ??
    meta.render ??
    ((a: Record<string, unknown>) => (Component ? createElement(Component, a) : null));

  let node: ReactNode = baseRender(args, context);

  // Decorators wrap from innermost (story) to outermost (meta); within a level
  // the first-defined decorator is the outermost, so apply each level in
  // reverse. Matches Storybook's decorator precedence.
  for (const level of [story.decorators, meta.decorators]) {
    if (!level) continue;
    for (let i = level.length - 1; i >= 0; i--) {
      const inner = node;
      const Wrapped: ComponentType = () => createElement(Fragment, null, inner);
      node = level[i](Wrapped, context);
    }
  }

  return node;
}

/**
 * One mounted story: label + isolated render. Memoized on its (stable) module
 * references so the progressive-mount re-renders below don't re-render — let
 * alone remount — stories that are already on screen.
 */
const RenderedStory = memo(function RenderedStory({
  meta,
  story,
  name,
}: {
  meta: Meta;
  story: StoryObj;
  name: string;
}) {
  return (
    <Stack gap="$sm">
      <Text c="$color11" fz={13} fontWeight="600">
        {humanize(name)}
      </Text>
      <StoryErrorBoundary label={humanize(name)}>
        <Box>{renderStory(meta, story)}</Box>
      </StoryErrorBoundary>
    </Stack>
  );
});

/** How many stories to mount in the first synchronous pass. */
const INITIAL_MOUNT = 2;

/**
 * Grow a count from `initial` up to `total`, one step per animation frame. Each
 * increment lands after the previous frame has painted, so the heavy mount work
 * of a whole section (e.g. 20 carousels) is spread across frames instead of
 * blocking the JS thread in one synchronous burst — the difference between a
 * smooth progressive reveal and an immediate freeze on Android.
 */
function useProgressiveCount(total: number, initial = INITIAL_MOUNT): number {
  const [count, setCount] = useState(() => Math.min(initial, total));
  useEffect(() => {
    if (count >= total) return;
    const raf = requestAnimationFrame(() => setCount((c) => Math.min(c + 1, total)));
    return () => cancelAnimationFrame(raf);
  }, [count, total]);
  return count;
}

/**
 * Renders every story in a Storybook module as one demo section: the component
 * title, then each named story under a small label. `mod` is the imported story
 * module (`import("@knitui/components/src/Button/Button.stories")`). Stories that
 * fill their container (e.g. maps) are rendered by `MapSection` instead — see
 * `sections.generated.tsx`.
 *
 * Stories mount progressively (one per frame) rather than all at once: a section
 * can hold dozens of heavy demos (carousels, maps), and mounting them in a single
 * synchronous pass froze the screen on open. The first {@link INITIAL_MOUNT} show
 * immediately so the screen is never blank.
 */
export function StorySection({ mod, title }: { mod: Record<string, unknown>; title: string }) {
  const meta = (mod.default ?? {}) as Meta;
  const stories = getStories(mod);
  const mounted = useProgressiveCount(stories.length);

  return (
    <Stack gap="$lg">
      <Title order={3}>{title}</Title>
      <Separator />
      {stories.slice(0, mounted).map(([name, story]) => (
        <RenderedStory key={name} meta={meta} story={story} name={name} />
      ))}
      {mounted < stories.length ? (
        <Text c="$color10" fz={12}>
          Loading {stories.length - mounted} more…
        </Text>
      ) : null}
    </Stack>
  );
}
