import { defineConfig } from "../../eslint.config.base.mjs";

/**
 * ESLint config for @knitui/emoji.
 * Extends the shared monorepo base; add package-specific overrides below.
 * (eslint-config-prettier is appended automatically after these.)
 */
export default defineConfig({
  // The ~3800 emoji modules under `src/emojis/` are machine-generated data
  // (`.js` geometry literals + tiny `.d.ts`), regenerated by
  // `scripts/generate-emoji.mjs` and never hand-edited. Linting them is pointless
  // and slow, so they're excluded here (the hand-written source — registry,
  // Emoji, internal renderers — is still linted).
  ignores: ["src/emojis/**"],
});
