import js from "@eslint/js";
import ts from "typescript-eslint";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import importX from "eslint-plugin-import-x";
import perfectionist from "eslint-plugin-perfectionist";
import prettierRecommended from "eslint-plugin-prettier/recommended";
import globals from "globals";

/**
 * Shared ESLint base for the whole monorepo.
 *
 * Every workspace has its own `eslint.config.mjs` that calls `defineConfig()`
 * from here, so per-package rules live next to the package while the shared
 * foundation stays in one place.
 *
 * Formatting is owned by Prettier (`.prettierrc.json`) but enforced THROUGH
 * ESLint: `eslint-plugin-prettier/recommended` is always appended LAST by
 * `defineConfig`, so it cannot be clobbered by a package's own overrides. It
 * runs Prettier as the `prettier/prettier` rule (autofixable) and bundles
 * `eslint-config-prettier` to switch off any stylistic ESLint rules that would
 * conflict. Net effect: `pnpm lint` flags formatting issues across every
 * package and `pnpm lint:fix` reformats them. `pnpm format` still works too.
 */
const base = [
  // Never lint build output, deps, or scratch dirs.
  {
    ignores: [
      "**/lib/**",
      "**/dist/**",
      "**/build/**",
      "**/.expo/**",
      "**/.next/**",
      "**/.turbo/**",
      "**/.tamagui/**",
      "**/coverage/**",
      "**/node_modules/**",
      "**/storybook-static/**",
      "**/web-build/**",
      // Expo CNG output — regenerated by `expo prebuild`, never hand-edited.
      "**/android/**",
      "**/ios/**",
      "**/*.d.ts",
      "tmp/**",
    ],
  },

  // Base JS + TypeScript recommendations for all source files.
  js.configs.recommended,
  ...ts.configs.recommended,

  // React-specific rules for components.
  {
    files: ["**/*.{ts,tsx,js,jsx}"],
    plugins: {
      react,
      "react-hooks": reactHooks,
      "import-x": importX,
      perfectionist,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2024,
      },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    settings: {
      react: { version: "detect" },
    },
    rules: {
      ...react.configs.recommended.rules,
      ...react.configs["jsx-runtime"].rules,
      ...reactHooks.configs.recommended.rules,

      // This is a TS RN/React-Native-Web kit — these are intentionally relaxed.
      "@typescript-eslint/no-explicit-any": "off",
      // `interface Props extends X {}` is a deliberate kit pattern.
      "@typescript-eslint/no-empty-object-type": [
        "error",
        { allowInterfaces: "with-single-extends" },
      ],
      // DOM-text concern; irrelevant for React Native <Text>.
      "react/no-unescaped-entities": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],

      // Common quality signals worth enforcing across the kit.
      "no-console": ["warn", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "smart"],
      "no-var": "error",
      "prefer-const": "error",
      "@typescript-eslint/consistent-type-imports": [
        "warn",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],

      // Import grouping & ordering via perfectionist (all autofixable via
      // `pnpm lint:fix`). perfectionist owns ordering; import-x owns the
      // structural hygiene it doesn't cover (duplicates, placement, spacing).
      "perfectionist/sort-imports": [
        "warn",
        {
          type: "natural",
          order: "asc",
          ignoreCase: true,
          newlinesBetween: 1,
          // `@knitui/*` workspace packages count as internal, not external.
          internalPattern: ["^@knitui/"],
          customGroups: [
            {
              groupName: "react",
              elementNamePattern: [
                "^react$",
                "^react-.+",
                "^react-native$",
                "^react-native-.+",
                "^expo$",
                "^expo-.+",
              ],
            },
            { groupName: "aliased", elementNamePattern: ["^~/", "^@/"] },
          ],
          groups: [
            "side-effect",
            "builtin",
            "react",
            "external",
            "internal",
            "aliased",
            ["parent", "sibling", "index"],
            "style",
            "unknown",
          ],
        },
      ],
      "perfectionist/sort-named-imports": ["warn", { type: "natural", order: "asc" }],
      "perfectionist/sort-exports": ["warn", { type: "natural", order: "asc" }],
      "perfectionist/sort-named-exports": ["warn", { type: "natural", order: "asc" }],
      "import-x/first": "warn",
      "import-x/newline-after-import": "warn",
      "import-x/no-duplicates": "warn",
    },
  },

  // Plain JS / CJS files (build-tool plugins, configs, scripts) are CommonJS by
  // nature — `require()` is correct here, and they run in Node.
  {
    files: ["**/*.{js,cjs}", "**/*.config.{js,mjs,cjs,ts}", "**/scripts/**"],
    languageOptions: { globals: { ...globals.node } },
    rules: {
      "no-console": "off",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-var-requires": "off",
    },
  },

  // Storybook stories use `render: () => { const [v] = useState() }`, which the
  // rules-of-hooks heuristic can't see as a component. Relax hooks rules here.
  {
    files: ["**/*.stories.{ts,tsx,js,jsx}", "**/*.story.{ts,tsx,js,jsx}"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
      "react-hooks/exhaustive-deps": "off",
    },
  },

  // Test files: relax a few rules that get in the way of test ergonomics.
  {
    files: ["**/*.{test,spec}.{ts,tsx,js,jsx}", "**/__tests__/**", "**/e2e/**"],
    languageOptions: { globals: { ...globals.jest, ...globals.node } },
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
];

/**
 * Build a flat config from the shared base plus any per-package overrides.
 * `eslint-plugin-prettier/recommended` is appended after the overrides so the
 * `prettier/prettier` rule (and the conflict-disabling `eslint-config-prettier`
 * it bundles) win no matter what a package adds.
 *
 * @param {...import("typescript-eslint").ConfigArray} overrides
 * @returns {import("typescript-eslint").ConfigArray}
 */
export function defineConfig(...overrides) {
  return ts.config(...base, ...overrides, prettierRecommended);
}

export default defineConfig();
