import * as Colors from "@tamagui/colors";
import { createThemes } from "@tamagui/theme-builder";

/**
 * The design-system theme suite, generated by `@tamagui/theme-builder`.
 *
 * `createThemes` does the heavy lifting we'd otherwise hand-roll:
 *  - interpolates each palette into the full semantic token set
 *    ($background / $color / $borderColor + hover/press/focus, $color1…$color12,
 *    transparent variants, $placeholderColor, $outlineColor, …);
 *  - produces the light/dark base themes;
 *  - produces one child theme per accent color, so `<Button theme="blue" />`
 *    nests into `light_blue` / `dark_blue` automatically.
 *
 * This is the idiomatic Tamagui theming system — semantic base themes plus
 * per-color sub-themes — rather than runtime color resolution.
 */
const palette = (light: Record<string, string>, dark: Record<string, string>) => ({
  light: Object.values(light),
  dark: Object.values(dark),
});

/**
 * The OVER-MEDIA palette — the tokens chrome painted ON TOP of media pixels uses
 * (the `@knitui/media` Video player). Video controls float over arbitrary video
 * content, so they can't ride the normal `$colorN` surface ramp the way a card
 * does: their backdrops must be translucent scrims and their glyphs a fixed light
 * color, regardless of the app theme. These values are therefore THEME-INDEPENDENT
 * (identical in light and dark) and are spread into every theme's `extra` so a
 * `$mediaScrim` / `$mediaOnScrim` reference resolves anywhere. This is the single
 * source of truth for the over-media look — media no longer hardcodes `rgba(…)` /
 * `"white"` literals. (Keeping the literals HERE, in the theme layer, is correct:
 * a `linear-gradient` / scrim color genuinely can't be a `$colorN` ramp token.)
 */
const OVER_MEDIA = {
  /** Text / glyph color for chrome on a dark scrim (the old `ON_DARK = "white"`). */
  mediaOnScrim: "white",
  /** Strong scrim — caption bubble + the opaque stop of the bottom gradient. */
  mediaScrim: "rgba(0,0,0,0.75)",
  /** Control surface — menu/flyout backdrops floating over the video. */
  mediaControlSurface: "rgba(0,0,0,0.7)",
  /** Full-frame overlay backdrop — the error / message scrim. */
  mediaOverlay: "rgba(0,0,0,0.6)",
  /** Light wash — the buffered-range underlay on the scrubber track. */
  mediaHighlight: "rgba(255,255,255,0.35)",
} as const;

export const themes = createThemes({
  base: {
    // Neutral grayscale ramp: background (1) → foreground (12).
    palette: {
      light: Object.values(Colors.gray),
      dark: Object.values(Colors.grayDark),
    },
    // Non-interpolated extras available on every theme. `blue` powers the
    // default selection highlight ($blue5); `red` gives every theme a stable
    // error palette ($red9) so input error borders stay red under any accent
    // without hardcoding a hex.
    extra: {
      light: {
        ...Colors.blue,
        ...Colors.red,
        // NB: do NOT name these `shadowColor` — that collides with RN's reserved
        // legacy shadow style prop, which makes Tamagui mangle the token's alpha
        // when it's referenced inside `boxShadow` on iOS (renders washed-out).
        dropShadowColor: "rgba(0,0,0,0.1)",
        dropShadowColorHover: "rgba(0,0,0,0.2)",
        ...OVER_MEDIA,
      },
      dark: {
        ...Colors.blueDark,
        ...Colors.redDark,
        dropShadowColor: "rgba(0,0,0,0.4)",
        dropShadowColorHover: "rgba(0,0,0,0.6)",
        ...OVER_MEDIA,
      },
    },
  },

  // Accent theme (the app's primary), available as `<Theme name="accent">`.
  accent: {
    palette: palette(Colors.blue, Colors.blueDark),
  },

  // One sub-theme per palette color → light_<name> / dark_<name>.
  childrenThemes: {
    blue: { palette: palette(Colors.blue, Colors.blueDark) },
    red: { palette: palette(Colors.red, Colors.redDark) },
    green: { palette: palette(Colors.green, Colors.greenDark) },
    orange: { palette: palette(Colors.orange, Colors.orangeDark) },
    pink: { palette: palette(Colors.pink, Colors.pinkDark) },
    purple: { palette: palette(Colors.purple, Colors.purpleDark) },
    teal: { palette: palette(Colors.teal, Colors.tealDark) },
    yellow: { palette: palette(Colors.yellow, Colors.yellowDark) },
    gray: { palette: palette(Colors.gray, Colors.grayDark) },
  },
});

export type AppThemes = typeof themes;
