import * as Colors from "@tamagui/colors";
import { createThemes } from "@tamagui/theme-builder";

import { OVER_MEDIA } from "./over-media";

/**
 * The design-system theme suite, generated by `@tamagui/theme-builder`.
 *
 * `createThemes` does the heavy lifting we'd otherwise hand-roll:
 *  - interpolates each palette into the full semantic token set
 *    ($background / $color / $borderColor + hover/press/focus, $color1…$color12,
 *    transparent variants, $placeholderColor, $outlineColor, …);
 *  - produces the light/dark base themes;
 *  - produces one child theme per accent color, so `<Button theme="blue" />`
 *    nests into `light_blue` / `dark_blue` automatically.
 *
 * This is the idiomatic Tamagui theming system — semantic base themes plus
 * per-color sub-themes — rather than runtime color resolution.
 *
 * PERF / `componentThemes: false`
 * ------------------------------
 * `createThemes` otherwise defaults `componentThemes` to Tamagui's
 * `defaultComponentThemes` — a 19-entry map (itself `@deprecated` upstream) that
 * CROSS-MULTIPLIES with every scheme × palette: 2 × 11 × 20 = 440 themes,
 * ~37.7k theme keys and ~2.5 MB of resolved `Variable` objects, all built
 * eagerly at module scope on every app start (and again by the babel/static
 * compiler). With it off: 22 themes, ~1.9k keys, ~0.2 MB.
 *
 * The kit does not want implicit component themes anyway — it routes colour
 * explicitly through `components/src/internal/variant-colors.ts` (`$color1…
 * $color12`). Nine `styled()` names DID collide with the default map and were
 * silently receiving a template offset (`Button`→surface3, `Card`/`ListItem`/
 * `Progress`→surface1, `Checkbox`→surface2, `SliderTrack`/`SliderThumb`/
 * `SwitchThumb`/`Tooltip`→inverse). Where that offset was load-bearing it is now
 * PINNED explicitly in the component's own `styled()` block, so turning the
 * generation off is visually neutral. Keep this in sync with the matching
 * `componentThemes: false` in `theme/create-theme.ts`.
 */
const palette = (light: Record<string, string>, dark: Record<string, string>) => ({
  light: Object.values(light),
  dark: Object.values(dark),
});

export const themes = createThemes({
  // See the note above — this is the single biggest lever on config build cost.
  componentThemes: false,

  base: {
    // Neutral grayscale ramp: background (1) → foreground (12).
    palette: {
      light: Object.values(Colors.gray),
      dark: Object.values(Colors.grayDark),
    },
    // Non-interpolated extras available on every theme. `blue` powers the
    // default selection highlight ($blue5); `red` gives every theme a stable
    // error palette ($red9) so input error borders stay red under any accent
    // without hardcoding a hex.
    extra: {
      light: {
        ...Colors.blue,
        ...Colors.red,
        // NB: do NOT name these `shadowColor` — that collides with RN's reserved
        // legacy shadow style prop, which makes Tamagui mangle the token's alpha
        // when it's referenced inside `boxShadow` on iOS (renders washed-out).
        dropShadowColor: "rgba(0,0,0,0.1)",
        dropShadowColorHover: "rgba(0,0,0,0.2)",
        ...OVER_MEDIA,
      },
      dark: {
        ...Colors.blueDark,
        ...Colors.redDark,
        dropShadowColor: "rgba(0,0,0,0.4)",
        dropShadowColorHover: "rgba(0,0,0,0.6)",
        ...OVER_MEDIA,
      },
    },
  },

  // Accent theme (the app's primary), available as `<Theme name="accent">`.
  accent: {
    palette: palette(Colors.blue, Colors.blueDark),
  },

  // One sub-theme per palette color → light_<name> / dark_<name>.
  childrenThemes: {
    blue: { palette: palette(Colors.blue, Colors.blueDark) },
    red: { palette: palette(Colors.red, Colors.redDark) },
    green: { palette: palette(Colors.green, Colors.greenDark) },
    orange: { palette: palette(Colors.orange, Colors.orangeDark) },
    pink: { palette: palette(Colors.pink, Colors.pinkDark) },
    purple: { palette: palette(Colors.purple, Colors.purpleDark) },
    teal: { palette: palette(Colors.teal, Colors.tealDark) },
    yellow: { palette: palette(Colors.yellow, Colors.yellowDark) },
    gray: { palette: palette(Colors.gray, Colors.grayDark) },
  },
});

export type AppThemes = typeof themes;
